[package]
name = "raytracer"
version = "0.1.0"
edition = "2018"

[dependencies]
rand = "0.7.3"
tobj = "2.0.2"
rayon = "1.4.1"
indicatif = "0.15.0"
image = "0.23.10"

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "scene"
harness = false

[profile.release]
opt-level = 3
