[package]
name = "raytracer"
version = "0.1.0"
authors = ["Sascha Hagedorn <mail@shagedorn.net>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
tobj = "2.0.2"
rayon = "1.4.0"
png = "0.16.7"
indicatif = "0.15.0"

[profile.release]
opt-level = 3
