[package]
name = "raytracer"
version = "0.1.0"
authors = ["Sascha Hagedorn <mail@shagedorn.net>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
dyn-clone = "1.0.2"
tobj = "2.0.2"

[profile.release]
opt-level = 3
